### ISSUE TITLE
Todo App 명세서 작성

### ISSUE THREAD

**Issue by bibidi77** [bibidi77/practice-issue#1]
## 만들고자 하는 기능
: Todo App 만들기

## 기능 구현을 위해 필요한 일
1. [x] Todo List 등록
2. [x] Todo List 조회
3. [x] Todo List 삭제
